name: Build

on:
  push:
    branches:
      - master
    paths-ignore:
      - '**.md'

jobs:
  Windows:
    name: Build Windows
    runs-on: windows-latest
    steps:
    - name: Install dependencies
      run: |
        echo $env:VCPKG_INSTALLATION_ROOT
        $env:VCPKG_DEFAULT_TRIPLET="x64-windows"
        vcpkg install glm cgal
    - name: Install Geoflow
      run: |
        Invoke-WebRequest https://github.com/geoflow3d/geoflow/releases/download/v0.1.6/Geoflow-win64.exe -OutFile geoflow-setup.exe
        .\geoflow-setup.exe /S
    - uses: actions/checkout@v1
    - name: Build
      run: |
        mkdir build
        cd build
        cmake .. -DCMAKE_TOOLCHAIN_FILE=C:\vcpkg\scripts\buildsystems\vcpkg.cmake -DVCPKG_TARGET_TRIPLET=x64-windows
        cmake --build . --target gfp_masb --parallel 4 --config Release
    - name: Create artifact
      uses: actions/upload-artifact@master
      with:
        name: gfp-masb-win64
        path: build/Release/gfp_masb.dll
